# This is a docker compose configuration for a simplified setup, where all services are in the same container.
services:
  unified:
    build:
      context: .
      dockerfile: Dockerfile.unified
    ports:
      - "8080:80" # nginx reverse proxy
