# This is a docker compose configuration for a simplified setup, where all services are in the same container.
services:
  unified:
    build:
      context: .
      dockerfile: Dockerfile.unified
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "5432:5432"
      - "8005:8005"
